//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика_задание2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class News_draft
    {
        public int ID { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Введите дату написания статьи")]
        public Nullable<System.DateTime> date { get; set; }

        [Required(ErrorMessage = "Введите заголовок статьи")]
        public string header { get; set; }

        [Required(ErrorMessage = "Введите тест статьи")]
        public string article { get; set; }
        public string author { get; set; }
        public bool publish { get; set; }
    }
}
